pets/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from photos import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^create-photo/', views.create_photo, name='create_photo'),
    url(r'^vote_photo/', views.vote_photo, name='vote_photo'),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

photos/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from model_utils.models import TimeStampedModel

class Photo(TimeStampedModel):

    user = models.ForeignKey('User', verbose_name=_('User'), on_delete=models.CASCADE)
    name = models.CharField(verbose_name=_('Name'), max_length=100, blank=True)
    file = models.FileField(
        verbose_name=_('attachment'), upload_to='media/',
        blank=True, null=True
    )

    @property
    def name_file(self):
        return self.file.url.split('/')[-1]

class User(TimeStampedModel):
    nickname = models.CharField(verbose_name=_('Name'), max_length=100, blank=True)

class Vote(TimeStampedModel):
    user = models.ForeignKey('User', verbose_name=_('User'), on_delete=models.CASCADE)
    photo = models.ForeignKey('Photo', verbose_name=_('Photo'), on_delete=models.CASCADE)

photos/views.py
from django.shortcuts import render

from django.http import HttpResponse

from django.db.models import Count
from django.views.generic.base import TemplateView
from django.views import generic
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from .models import Photo, User, Vote

import json, datetime

class HomePageView(TemplateView):

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = Photo.objects.annotate(count=Count('vote__id')).order_by('-count')
        return context

home = HomePageView.as_view()

class CreatePhotoView(generic.View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CreatePhotoView, self).dispatch(request=request)

    def post(self, request):
        dic = {}
        nickname = self.request.POST['nickname']
        pet = self.request.POST['pet']
        ffile = self.request.FILES['a_file']
        user = User.objects.filter(nickname = nickname)
        if user.exists():
            user = user.first()
        else:
            user = User.objects.create(nickname = nickname)
        Photo.objects.create(user = user, name = pet, file = ffile)
        dic['success'] = True
        return HttpResponse(content=json.dumps(dic), content_type='application/json; charset=utf-8')

create_photo = CreatePhotoView.as_view()


class VotePhotoView(generic.View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(VotePhotoView, self).dispatch(request=request)

    def post(self, request):
        dic = {}
        nickname = self.request.POST['nickname']
        id = self.request.POST['id']
        photo = Photo.objects.get(id = id)
        user = User.objects.filter(nickname = nickname)
        if user.exists():
            user = user.first()
        else:
            user = User.objects.create(nickname = nickname)
        vote = Vote.objects.filter(user = user, photo = photo)
        if vote.exists():
            dic['success'] = False
        else:
            vote = Vote.objects.create(user = user, photo = photo)
            dic['success'] = True
        return HttpResponse(content=json.dumps(dic), content_type='application/json; charset=utf-8')

vote_photo = VotePhotoView.as_view()

photos/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PETS SITE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
    <script>

    $(document).on('click', '.vote-btn', function(e) {
      var $this = $(this)
      , id = $this.data('id')
      , url = $this.data('url');

      Swal.fire({
        title: 'Dame tu nickname',
        input: 'text',
        inputAttributes: {
          autocapitalize: 'off'
        },
        showCancelButton: true,
        confirmButtonText: 'Dale!',
        cancelButtonText: 'Cancelar',
        showLoaderOnConfirm: true,
      }).then((result) => {
        if (result.value) {
          nickname = result.value;
          var myFormData = new FormData();
          myFormData.append('nickname', nickname);
          myFormData.append('id', id);
          $.ajax({
            url: url,
            type: 'POST',
            processData: false,
            contentType: false,
            data: myFormData,
          }).done(function(json) {
            if (json.success) {
              location.reload();
            }
            else{
              Swal.fire({
                type: 'error',
                title: 'SORY',
                text: 'Ya votaste.'
              })
            }
          })
        }
      });
    });

    $(document).on('click', '#upload-photo', function(e) {
      var $this = $(this)
      , url = $this.data('url')
      ,nickname = ""
      , pet = ""
      , file = "";

      Swal.fire({
        title: 'Dame tu nickname',
        input: 'text',
        inputAttributes: {
          autocapitalize: 'off'
        },
        showCancelButton: true,
        confirmButtonText: 'Dale!',
        cancelButtonText: 'Cancelar',
        showLoaderOnConfirm: true,
      }).then((result) => {
        if (result.value) {
          nickname = result.value
          Swal.fire({
            title: 'Dame el nombre de tu mascota',
            input: 'text',
            inputAttributes: {
              autocapitalize: 'off'
            },
            showCancelButton: true,
            confirmButtonText: 'Dale!',
            cancelButtonText: 'Cancelar',
            showLoaderOnConfirm: true,
          }).then((result) => {
            if (result.value) {
              pet = result.value
              Swal.fire({
                title: 'Sube la imagen',
                input: 'file',
                inputAttributes: {
                  accept: 'image/*',
                  'aria-label': 'Upload your profile picture'
                },
                showCancelButton: true,
                confirmButtonText: 'Dale!',
                cancelButtonText: 'Cancelar',
                showLoaderOnConfirm: true,
              }).then((result) => {
                if (result.value) {
                  file = result.value;
                  functionUpload(nickname, pet, file, url);
                }
              })
            }
          })
        }
      })
    });

    function functionUpload(nickname, pet, file, url) {
      var myFormData = new FormData();
      myFormData.append('pet', pet);
      myFormData.append('nickname', nickname);
      myFormData.append('a_file', file);

      $.ajax({
        url: url,
        type: 'POST',
        processData: false,
        contentType: false,
        data: myFormData,
      }).done(function(json) {
        location.reload();
      })
    }

    </script>
  </head>
  <body>
  <header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
          <strong>Album</strong>
        </a>
      </div>
    </div>
  </header>

<main role="main">

<section class="jumbotron text-center" style="padding: 2px !important">
  <div class="container">
    <h1 class="jumbotron-heading">Buena!</h1>
    <p class="lead text-muted">Apreta el cosito si quieres subir una foto</p>
    <p>
      <a id="upload-photo" class="btn btn-primary my-2" data-url="{% url 'create_photo' %}">Dale!</a>
    </p>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      {% for photo in photos %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{{photo.file.url}}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
          <div class="card-body">
            <p class="card-text"><b>{{photo.name}}</b><br><small>Dueño: {{photo.user.nickname}}</small></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary vote-btn" data-id="{{photo.id}}" data-url="{% url 'vote_photo' %}">Me gustó</button>
              </div>
              <small class="text-muted">{{photo.vote_set.count}} Votos</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</div>

</main>

<footer class="text-muted">
<div class="container">
  <p>Patricio Vargas Pino - 2019 - Del template más simple de bootstrap</p>
</div>
</footer>
</html>